name: CI/CD - Spring Boot

on:
  push:
    branches: [main]           # Déclenchement sur push dans la branche main
  pull_request:                # Ou sur une Pull Request

jobs:
  build-test-sonar-docker:
    runs-on: ubuntu-latest     # Machine virtuelle utilisée par GitHub Actions

    steps:
      - name: Cloner le code
        uses: actions/checkout@v3

      - name: Installer Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17     # Version recommandée pour Spring Boot
          distribution: temurin

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Compiler & Tester
        run: mvn clean install  # Compile et exécute les tests JUnit

      - name: Analyse SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=SpringBack \
            -Dsonar.host.url=http://<IP_SONAR>:9000 \
            -Dsonar.login=$SONAR_TOKEN

      - name: Construire image Docker
        run: docker build -t yourdockerhub/springback:latest .

      - name: Login DockerHub + Push
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push yourdockerhub/springback:latest

