name: CI/CD - Spring Boot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-sonar-docker:
    runs-on: self-hosted  

    steps:
      - name: Cloner le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compiler & Générer JaCoCo
        run: mvn clean verify jacoco:report

      - name: Vérifier accès SonarQube
        run: |
          curl -f http://sonarqube.192.168.224.163.nip.io:9000 || echo "⚠️ SonarQube unreachable"

      - name: Analyse SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=ahmed-springtestt \
            -Dsonar.host.url=http://sonarqube.192.168.224.163.nip.io:9000 \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Construire image Docker
        run: docker build -t ahmedsouid1/springback:latest .

      - name: Login DockerHub + Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push ahmedsouid1/springback:latest
